/*
 * settings.h
 *
 *  Created on: 04.06.2019
 *      Author: student
 */

#include <cstdio>

// gameplay

#define GAME_DURATION_S 30
#define MAGAZINE_SIZE 6
#define SPAWN_PERCENTAGE 20

#define MAP_SCROLL_SPEED 10
#define CROSSHAIR_SCROLL_SPEED 5

#define GROUSE_FLY_SPEED 2
#define GROUSEFLY_ANIMATION_SPEED 2
#define GROUSERUN_ANIMATION_SPEED 1

#define SENSOR_TRIGGER_G 400
#define SENSOR_TRIGGER_JOY 200



/*
 * Fix config! Do not change these configuration.
 */

#define DISPLAY_SIZE 128
#define TRANSPARENT_COLOR 0x2589 //green
#define MENU_BACKGROUND_COLOR 0x22BE
#define MENU_FONT_UNMARKED 0x8FFE
#define MENU_FONT_MARKED 0x05A3
#define MENU_CHECKBOX_CHECK 0xC000
#define FONT_COLOR_POINTS 0x0000

#define MAP_START_X 128
#define MAP_START_Y 44

#define CROSSHAIR_START_X 56
#define CROSSHAIR_START_Y 56

#define GROUSE_FISHING_START_X 130
#define GROUSE_FISHING_START_Y 120

#define GROUSERUN_RIGHT_START_X 400
#define GROUSERUN_RIGHT_START_Y 120

#define GROUSERUN_LEFT_START_X_BOT 0
#define GROUSERUN_LEFT_START_Y_BOT 170

#define GROUSERUN_LEFT_START_X_TOP 0
#define GROUSERUN_LEFT_START_Y_TOP 90

#define GROUSE_START_X 10
#define GROUSE_START_Y 39

#define MENU_ENTRY_X 53
#define MENU_ENTRY_Y_START 30
#define MENU_ENTRY_Y_SETTINGS 55
#define MENU_ENTRY_Y_HIGHSCORE 80

#define MENU_ENTRY_X_AUTO 10
#define MENU_ENTRY_Y_AUTO 10
#define MENU_ENTRY_X_OK 60
#define MENU_ENTRY_Y_OK 100

#define MENU_ENTRY_CHECKBOX_X 80
#define MENU_ENTRY_CHECKBOX_Y 2

#define MENU_ENTRY_Y_NAVIGATION 43
#define MENU_ENTRY_Y_CROSSHAIR 70

#define MENU_SYMBOL_X 80
#define MENU_SYMBOL_NAVIGATION_Y 35
#define MENU_SYMBOL_CROSSHAIR_Y 62

#define MENU_SYMBOL_SWITCH_Y 49
#define MENU_SYMBOL_SWITCH_X 102



