/*
 * settings.h
 *
 *  Created on: 04.06.2019
 *      Author: student
 */

#include <cstdio>

// start positioin config

#define MAP_START_X 128
#define MAP_START_Y 44

#define CROSSHAIR_START_X 56
#define CROSSHAIR_START_Y 56

// gameplay

#define MAP_SCROLL_SPEED 10
#define CROSSHAIR_SCROLL_SPEED 5
#define GROUSE_FLY_SPEED 2

#define SENSOR_TRIGGER_G 400
#define SENSOR_TRIGGER_JOY 200

#define GROUSEFLY_ANIMATION_SPEED 2
#define GROUSERUN_ANIMATION_SPEED 1


//game config
#define MAGAZINE_SIZE 6


//fix config

#define DISPLAY_SIZE 128
#define TRANSPARENT_COLOR 0x2589 //green
#define MENU_BACKGROUND_COLOR 0x1080
#define MENU_FONT_UNMARKED 0x0000
#define MENU_FONT_MARKED 0xFFFF
#define MENU_CHECKBOX_CHECK 0xFF00



// item positioning
#define GROUSE_FISHING_START_X 130
#define GROUSE_FISHING_START_Y 120

#define GROUSERUN_RIGHT_START_X 400
#define GROUSERUN_RIGHT_START_Y 120

#define GROUSERUN_LEFT_START_X_BOT 0
#define GROUSERUN_LEFT_START_Y_BOT 170

#define GROUSERUN_LEFT_START_X_TOP 0
#define GROUSERUN_LEFT_START_Y_TOP 90

#define GROUSE_START_X 10
#define GROUSE_START_Y 39

#define MENU_ENTRY_X 53
#define MENU_ENTRY_Y_START 30
#define MENU_ENTRY_Y_SETTINGS 55
#define MENU_ENTRY_Y_HIGHSCORE 80

#define MENU_ENTRY_X_AUTO 10
#define MENU_ENTRY_Y_AUTO 20
#define MENU_ENTRY_X_OK 50
#define MENU_ENTRY_Y_OK 95

#define MENU_ENTRY_CHECKBOX_X 90
#define MENU_ENTRY_CHECKBOX_Y 12

#define MENU_ENTRY_Y_NAVIGATION 55
#define MENU_ENTRY_Y_CROSSHAIR 80





